#include <stdio.h>

int max(int x, int y) {
    return (x > y) ? x : y;
}

int max_of_four(int a, int b, int c, int d) {
    int max_ab = max(a, b);
    int max_cd = max(c, d);
    return max(max_ab, max_cd);
}

int main() {
    int a, b, c, d;

    scanf("%d", &a);
    scanf("%d", &b);
    scanf("%d", &c);
    scanf("%d", &d);

    int result = max_of_four(a, b, c, d);
    printf("%d\n", result);

    return 0;
}
